### ISSUE TITLE
Support array of patterns

### ISSUE THREAD

**Issue by Neaox** [thriqon/random-word-generator#2]
Currently unless you change the pattern back and forth with each iteration there is no way to get a combination of words that start with any letter. The default pattern only creates words that start with consonants.

You can change the pattern but if you truly want a random combination you would need to switch back and forth with each iteration,

It would be helpful to support an array of patterns which are then randomly chosen from when generating a word. That way, by default you could have two patterns to allow for generating words starting with any letter of the alphabet.

**Comment by thriqon** [comment]
You can actually define a group of all characters and take that as the start of your pattern. Please take a look into the tests, namely `generation.js`. You can see the syntax for custom groups there.

The default settings are not tailored for this use case, thats true.

**Comment by thriqon** [comment]
For example (this does not generate pronouncable words, though):

````javascript
var Generator = require('random-word-generator');

var g = new Generator();
g.group('a', 'abcdefghijklmnopqrstuvwxyz');
g.pattern('Aaaaaaaaaa');

console.log(g.generate());
console.log(g.generate());
console.log(g.generate());
````
