### ISSUE TITLE
You should explain...

### ISSUE THREAD

**Issue by nickperkinslondon** [thriqon/random-word-generator#3]
There are several "random word" packages on npm that randomly choose a word from a dictionary.  You should explain better that your package is different -- that it makes up new words that don't exist -- because it's not obvious right away.  Specifically when you say that it "returns a random word" -- that does not make it obvious -- it sounds like you are doing what the others do.  Also, give more than one example output in your description -- a single made-up word is not immediately distinguishable from a randomly chosen dictionary word ( it might be a real word that I just don't know ) -- but a whole list of them would give a more correct impression.   Anyway, thanks for the package -- cool stuff.

**Comment by thriqon** [comment]
Thanks, I've added some docs to the `README.md` for this in #8 .
